version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: crm_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-postgres:
    image: postgres:16
    container_name: crm_test_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - '${TEST_POSTGRES_PORT}:5432'
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: crm_redis
    restart: unless-stopped
    command: >
      sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    env_file:
      - .env
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  test_postgres_data:
  redis_data:
